formats:
  v1:
    structure:
      start_date: {}
      end_date: {}
      nights: {}
      guests: {}
      adults: {}
      children: {}
      infants: {}
      status: {}
      guest:
        id: {}
        first_name: {}
        last_name: {}
        phone: {}
        email: {}
      currency: {}
      payout_price: {}
      security_price: {}
      total_price: {}
    mappings:
      guest:
        email: guest.email
        first_name: guest.first_name
        last_name: guest.last_name
        phone_numbers: guest.phone
      reservation:
        start_date: start_date
        end_date: end_date
        number_of_nights: nights
        number_of_guests: guests
        number_of_adults: adults
        number_of_infants: infants
        number_of_children: children
        status: status
        currency: currency
        payout_price: payout_price
        security_price: security_price
        total_price: total_price

  v2:
    structure:
      reservation:
        start_date: {}
        end_date: {}
        expected_payout_amount: {}
        guest_details:
          localized_description: {}
          number_of_adults: {}
          number_of_children: {}
          number_of_infants: {}
        guest_email: {}
        guest_first_name: {}
        guest_id: {}
        guest_last_name: {}
        guest_phone_numbers: []
        listing_security_price_accurate: {}
        host_currency: {}
        nights: {}
        number_of_guests: {}
        status_type: {}
        total_paid_amount_accurate: {}
    mappings:
      guest:
        email: reservation.guest_email
        first_name: reservation.guest_first_name
        last_name: reservation.guest_last_name
        phone_numbers: reservation.guest_phone_numbers
      reservation:
        start_date: reservation.start_date
        end_date: reservation.end_date
        localized_description: reservation.guest_details.localized_description
        number_of_nights: reservation.nights
        number_of_guests: reservation.number_of_guests
        number_of_adults: reservation.guest_details.number_of_adults
        number_of_infants: reservation.guest_details.number_of_infants
        number_of_children: reservation.guest_details.number_of_children
        status: reservation.status_type
        currency: reservation.host_currency
        payout_price: reservation.expected_payout_amount
        security_price: reservation.listing_security_price_accurate
        total_price: reservation.total_paid_amount_accurate

  hotels_com:
    structure:
      booking_info:
        reservation_dates:
          check_in: {}
          check_out: {}
          total_nights: {}
        price_details:
          currency_code: {}
          host_payout: {}
          security_deposit: {}
          total_amount: {}
        occupancy:
          total: {}
          breakdown:
            adult_count: {}
            child_count: {}
            infant_count: {}
        booking_status: {}
        customer:
          profile:
            customer_id: {}
            name:
              given_name: {}
              family_name: {}
            contact:
              email_address: {}
              telephone: []
    mappings:
      guest:
        email: "booking_info.customer.profile.contact.email_address"
        first_name: "booking_info.customer.profile.name.given_name"
        last_name: "booking_info.customer.profile.name.family_name"
        phone_numbers: "booking_info.customer.profile.contact.telephone"

      reservation:
        start_date: "booking_info.reservation_dates.check_in"
        end_date: "booking_info.reservation_dates.check_out"
        number_of_nights: "booking_info.reservation_dates.total_nights"
        number_of_guests: "booking_info.occupancy.total"
        number_of_adults: "booking_info.occupancy.breakdown.adult_count"
        number_of_children: "booking_info.occupancy.breakdown.child_count"
        number_of_infants: "booking_info.occupancy.breakdown.infant_count"
        status: "booking_info.booking_status"
        currency: "booking_info.price_details.currency_code"
        payout_price: "booking_info.price_details.host_payout"
        security_price: "booking_info.price_details.security_deposit"
        total_price: "booking_info.price_details.total_amount"
